In [2]:
!python -m pip install xlrd pandas scikit-learn matplotlib

Requirement already satisfied: xlrd in c:\python310\lib\site-packages (2.0.1)
Requirement already satisfied: pandas in c:\python310\lib\site-packages (1.5.0)
Requirement already satisfied: scikit-learn in c:\python310\lib\site-packages (1.1.3)
Collecting matplotlib
  Downloading matplotlib-3.6.1-cp310-cp310-win_amd64.whl (7.2 MB)
     ---------------------------------------- 7.2/7.2 MB 10.2 MB/s eta 0:00:00
Requirement already satisfied: scipy in c:\python310\lib\site-packages (1.9.3)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\miroi\appdata\roaming\python\python310\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\python310\lib\site-packages (from pandas) (2022.4)
Requirement already satisfied: numpy>=1.21.0 in c:\python310\lib\site-packages (from pandas) (1.23.3)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\python310\lib\site-packages (from scikit-learn) (3.1.0)
Requirement already satisfied: joblib>=1.0.0 in c:\python310\lib\site-packages (from scikit-learn) (1.2.0)
Collecting cycler>=0.10
  Downloading cycler-0.11.0-py3-none-any.whl (6.4 kB)
Collecting fonttools>=4.22.0
  Downloading fonttools-4.38.0-py3-none-any.whl (965 kB)
     ------------------------------------- 965.4/965.4 kB 15.2 MB/s eta 0:00:00
Requirement already satisfied: packaging>=20.0 in c:\users\miroi\appdata\roaming\python\python310\site-packages (from matplotlib) (21.3)
Requirement already satisfied: pyparsing>=2.2.1 in c:\users\miroi\appdata\roaming\python\python310\site-packages (from matplotlib) (3.0.9)
Collecting kiwisolver>=1.0.1
  Downloading kiwisolver-1.4.4-cp310-cp310-win_amd64.whl (55 kB)
     ---------------------------------------- 55.3/55.3 kB ? eta 0:00:00
Collecting contourpy>=1.0.1
  Downloading contourpy-1.0.5-cp310-cp310-win_amd64.whl (164 kB)
     ---------------------------------------- 164.1/164.1 kB ? eta 0:00:00
Collecting pillow>=6.2.0
  Downloading Pillow-9.2.0-cp310-cp310-win_amd64.whl (3.3 MB)
     ---------------------------------------- 3.3/3.3 MB 10.4 MB/s eta 0:00:00
Requirement already satisfied: six>=1.5 in c:\users\miroi\appdata\roaming\python\python310\site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)
Installing collected packages: pillow, kiwisolver, fonttools, cycler, contourpy, matplotlib

WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'c:\\Python310\\share\\man'
Consider using the `--user` option or check the permissions.

WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)

[notice] A new release of pip available: 22.2.2 -> 22.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [1]:
import pandas as pd

df = pd.read_excel('../data/hawaii-5-11-22.xls', sheet_name='Complete')

numerical = df[['ISLAND', 'VOLCANO', 'STAGE', 'KEA LOA TREND', 'LATITUDE MIN', 'LATITUDE MAX', 'Latitude (Avg)', 'LONGITUDE MIN', 'LONGITUDE MAX', 'Longitude (Avg)', 'ELEVATION MIN', 'ELEVATION MAX', 'MIN. AGE (YRS.)', 'MAX. AGE (YRS.)', 'AGE', 'SIO2(WT%)', 'TIO2(WT%)', 'B2O3(WT%)', 'AL2O3(WT%)', 'CR2O3(WT%)', 'FE2O3(WT%)', 'FEO(WT%)', 'FEOT(WT%)', 'FeO*', 'CAO(WT%)', 'MGO(WT%)', 'MNO(WT%)', 'NIO(WT%)', 'K2O(WT%)', 'NA2O(WT%)', 'P2O5(WT%)', 'Total_wt', 'Total2_wt', 'H2O(WT%)', 'H2OP(WT%)', 'H2OM(WT%)', 'H2OT(WT%)', 'CO2(WT%)', 'CO1(WT%)', 'F(WT%)', 'CL(WT%)', 'CL2(WT%)', 'OH(WT%)', 'CH4(WT%)', 'SO2(WT%)', 'SO3(WT%)', 'SO4(WT%)', 'S(WT%)', 'LOI(WT%)', 'VOLATILES(WT%)', 'O(WT%)', 'OTHERS(WT%)', 'HE(CCM/G)', 'HE(CCMSTP/G)', 'HE3(CCMSTP/G)', 'HE3(AT/G)', 'HE4(CCM/G)', 'HE4(CCMSTP/G)', 'HE4(AT/G)', 'HE4(MOLE/G)', 'HE4(NCC/G)', 'HE(NCC/G)', 'LI(PPM)', 'BE(PPM)', 'B(PPM)', 'C(PPM)', 'CO2(PPM)', 'F(PPM)', 'NA(PPM)', 'MG(PPM)', 'AL(PPM)', 'P(PPM)', 'S(PPM)', 'CL(PPM)', 'K(PPM)', 'CA(PPM)', 'SC(PPM)', 'TI(PPM)', 'V(PPM)', 'CR(PPM)', 'MN(PPM)', 'FE(PPM)', 'CO(PPM)', 'NI(PPM)', 'CU(PPM)', 'ZN(PPM)', 'GA(PPM)', 'GE(PPM)', 'AS(PPM)', 'SE(PPM)', 'BR(PPM)', 'RB(PPM)', 'SR(PPM)', 'Y(PPM)', 'ZR(PPM)', 'NB(PPM)', 'MO(PPM)', 'RU(PPM)', 'RH(PPM)', 'PD(PPM)', 'AG(PPM)', 'CD(PPM)', 'IN(PPM)', 'SN(PPM)', 'SB(PPM)', 'TE(PPM)', 'I(PPM)', 'CS(PPM)', 'BA(PPM)', 'LA(PPM)', 'CE(PPM)', 'PR(PPM)', 'ND(PPM)', 'SM(PPM)', 'EU(PPM)', 'GD(PPM)', 'TB(PPM)', 'DY(PPM)', 'HO(PPM)', 'ER(PPM)', 'TM(PPM)', 'YB(PPM)', 'LU(PPM)', 'HF(PPM)', 'TA(PPM)', 'W(PPM)', 'RE(PPM)', 'OS(PPM)', 'IR(PPM)', 'PT(PPM)', 'AU(PPM)', 'HG(PPM)', 'TL(PPM)', 'PB(PPM)', 'BI(PPM)', 'TH(PPM)', 'U(PPM)', 'ND143_ND144', 'ND143_ND144_INI', 'Epsilon_Nd (calculated) (incorrect)', 'SR87_SR86', 'SR87_SR86_INI', 'PB206_PB204', 'PB206_PB204_INI', 'PB207_PB204', 'PB207_PB204_INI', 'PB208_PB204', 'PB208_PB204_INI', 'OS184_OS188', 'OS186_OS188', 'OS187_OS186', 'OS187_OS188', 'RE187_OS186', 'RE187_OS188', 'HF176_HF177', 'Epsilon_Hf (calculated) (incorrect)', 'HE3_HE4', 'HE3_HE4(R/R(A))', 'HE4_HE3', 'HE4_HE3(R/R(A))', 'K40_AR40', 'AR40_K40', 'UNIQUE_ID', 'Isotope_presence', 'SrO (%)', 'BaO (%)', 'FeO*/MgO', 'Sr/Y', 'Na2O + K2O', 'Nb/U', 'Zr/Nb', 'Sr/Nb', 'Sm/Yb', 'Sr/Nb']]

numerical.head()

,ISLAND,VOLCANO,STAGE,KEA LOA TREND,LATITUDE MIN,LATITUDE MAX,Latitude (Avg),LONGITUDE MIN,LONGITUDE MAX,Longitude (Avg),...,SrO (%),BaO (%),FeO*/MgO,Sr/Y,Na2O + K2O,Nb/U,Zr/Nb,Sr/Nb,Sm/Yb,Sr/Nb
0,1.0,1.0,0.0,2.0,19.91,19.91,19.91,-156.3,-156.3,-156.3,...,NaN,NaN,0.601753,NaN,1.98,NaN,NaN,NaN,NaN,NaN
1,1.0,1.0,0.0,2.0,19.91,19.91,19.91,-156.3,-156.3,-156.3,...,NaN,NaN,1.728696,NaN,3.08,NaN,NaN,NaN,NaN,NaN
2,1.0,1.0,0.0,2.0,19.91,19.91,19.91,-156.3,-156.3,-156.3,...,NaN,NaN,1.718224,NaN,3.04,NaN,NaN,NaN,NaN,NaN
3,1.0,1.0,0.0,2.0,19.91,19.91,19.91,-156.3,-156.3,-156.3,...,NaN,NaN,1.671799,NaN,3.03,NaN,NaN,NaN,NaN,NaN
4,1.0,1.0,0.0,2.0,19.91,19.91,19.91,-156.3,-156.3,-156.3,...,NaN,NaN,1.716137,NaN,3.07,NaN,NaN,NaN,NaN,NaN